name: publish-gh-pages
on:
  push:
    branches:
     - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: subdir/package-lock.json
    - run: npm install
    - run: npm run deploy